### PR TITLE
[*] HTML: Refactor page layout

### LINKED ISSUE #15: Semantic HTML markup
Semantic elements like `<aside>`, `<address>` should be used more often, for example on page laoyout columns

### PR DESCRIPTION
**Pull request by gskema**
Main compatibility concerns:
- do any of the module use removed elements?
- can we change the `z-index` of `#header`?

Resolves #15

### CODE REVIEW

**Comment by kpodemski** [comment]
Well, in my opinion no module shouldn't remove elements, it's against logic, it should _add_ elements.

If you changed `z-index` from `5003` to `1` it's ok in my opinion.

**Comment by gskema** [comment]
Sorry, I meant if any of the modules use `removed` elements or have CSS selectors for them.

`.bottom-footer, .footer-container, .columns-container, .center_column, .header-container, #page`

**Comment by kpodemski** [comment]
I don't think so, maaaaybe `#page` but I doubt it

**Comment by gskema** [comment]
ok then, we'll fix it when it breaks :D

**Pull request merged**
