### PR TITLE
FO: Couldn't delete compared products on Firefox

### PR DESCRIPTION
**Pull request by kpodemski**
I couldn't delete all products from comparison on Firefox, try:
1. Add two or more products
2. Delete one by one in Chrome, everything ok.
3. Delete one by one in Firefox, they'll "restore" after you will delete the last one

### CODE REVIEW

**Comment by gskema** [comment]
Maybe it's a cookie problem? Does it work with default theme?

**Comment by kpodemski** [comment]
Yes it does work with default theme, you've refactored this code from what I see and it's totaly different than this from default-bootstrap, open your demo on Firefox and try to delete products.

https://gskema.com/prestashop/community-theme/en/products-comparison?compare_product_list=1%7C2

:)

**Comment by gskema** [comment]
Works for me Firefox. Perhaps we should move this line to `success` callback:

https://github.com/PrestaShop/community-theme-16/blob/dev/themes/community-theme-16/js/products-comparison.js#L69

Maybe the ajax is processed after the page request. I don't really know how the product ID list works in PHP :(

**Comment by kpodemski** [comment]
Hmm, weird, maybe it is OS related? I don't know, for me, my client and one more after you click last "X" products are restored. So i am deleting "Blouse", I have only one product, I am deleting "Faded Short Sleeves T-shirt" and once again i have two products.

**Comment by gskema** [comment]
Perhaps we should try using `decodeURIComponent` and `encodeURIComponent` like i  here: https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/themes/default-bootstrap/js/products-comparison.js#L85-L107

**Comment by schibu83** [comment]
Tryed this with FF 47.0 on OS X 10.11.5:

First delete of comparison worked fine. The next tests always had the same issue: After deleting the last product, one product was "restored". Deleting that restored product was then final an the comparison-page was empty. After 4 times testing this with different products it works now fine and the issue is not reproducable anymore :-O

**Comment by gskema** [comment]
Any progress on the issue? Can you comment the fix (looks weird)?

**Comment by kpodemski** [comment]
@gskema no time :/ i'll back to this issue later today or tomorrow

**Comment by kpodemski** [comment]
@gskema i didn't found any good solution for this problem tbh :/ this solution from PR sometimes works, sometimes not, adding `encodeURIComponent` etc. doesn't really help

**Comment by gskema** [comment]
Have you tried debugging (outputting) the variables in question? For example, does `params` variable differ in Firefox?

**Comment by kpodemski** [comment]
no... you know what is funny? I've added `alert('All products deleted');` and it is working all the time

javascript... :scream:

**Comment by gskema** [comment]
So should we close this?

**Pull request closed without merging**
