### PR TITLE
Update header.tpl

### PR DESCRIPTION
**Pull request by Jonadabe**
Adding canonical link to each page

### CODE REVIEW

**Comment by gskema** [comment]
Hello, thank you for your contribution.

Would you care to explain how this patch would help with SEO canonical links?

**Comment by kpodemski** [comment]
I don't think it should be controlled via theme, I know that there are plenty of SEO modules which have mechanism for canonical urls

**Comment by Jonadabe** [comment]
Hi gskema,

You can see it here:
[Moz](https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps)
[Google](https://support.google.com/webmasters/answer/139066?hl=en)

Thank you.

**Comment by gskema** [comment]
Hello,

yes we do know what is a `canonical` tag and when to use, that's why we were asking what was the purpose of your change, because it doesn't make any sense in terms of SEO.
It's not compatible with modules which output canonical tag. The canonical link should not be the current URL.

**Comment by Jonadabe** [comment]
Ok, I see.

Thanks.

**Comment by gskema** [comment]
@Jonadabe 

Thanks for the interest though. As for SEO, there won't any major changes in this theme except maybe some modifications of microdata markup.

**Pull request closed without merging**
