### PR TITLE
Update index.tpl

### PR DESCRIPTION
**Pull request by vytsci**
This row lacks columns. That makes content to drop out of edges.

### CODE REVIEW

**Comment by kpodemski** [comment]
I'm not convinced about this change, i never had any issues with content moving outside of the edge, can you show me some example before and after and markup behind it?

**Comment by vytsci** [comment]
Install theme on fresh prestashop. And you will see that products photos goes outside of boundaries of website.

**Comment by vytsci** [comment]
screenshot from 2017-03-28 18-44-55
screenshot from 2017-03-28 18-45-04

**Comment by vytsci** [comment]
Looks terrible

**Pull request merged**
