### PR TITLE
TPL: fix menu translate

### PR DESCRIPTION
**Pull request by Davidoseq**
"Menu" doesnt load to translator in administration Translate

### CODE REVIEW

**Comment by gskema** [comment]
Blocktopmenu is not used in this theme, why do you want to use it?

**Comment by Davidoseq** [comment]
I'm sorry, I thought that it is used.

**Comment by gskema** [comment]
No problem. Can I close your PR?

**Comment by Davidoseq** [comment]
Yeah of course ;) Thx

**Pull request closed without merging**
