### PR TITLE
[+] FO: add a SCSS mixin for font-face

### PR DESCRIPTION
**Pull request by francoispeyret**
I often need to change the typography of the Theme.

**a mixin font-face is more efficient and is better for optimizations scores**
compared to an import in the `<head>`

### CODE REVIEW

**Comment by gskema** [comment]
Hello,

I think such a feature is a personal preference. Myself - I mostly use Google Fonts or font loaders. While it doesn't increase the final theme size, I don't know whether we should have this. If most developers used this, then yes, but I don't they do. We need some more opinions.

**Comment by kpodemski** [comment]
I'm also more for webfontloader and other libraries like this one, i'm not using font-face directly in styles anymore

**Comment by julienbourdeau** [comment]
I prefer Sass mixin too, I don't like loading font front googlefont usually (regardless the performance).
Even if I agree it's a personal preference, adding a sass mixin doesn't mean you can't use `<head>` loading. At least all themes will load fonts the same way in CSS.

**Comment by francoispeyret** [comment]
I think you are right. My "pull-request" is not consistent
i close.

**Pull request closed without merging**
