### PR TITLE
Remove jquery uniform - resolves #16

### LINKED ISSUE #16: Remove jquery.uniform
Let developers decice how to style form elements.

### PR DESCRIPTION
**Pull request by kpodemski**
@gskema please review

### CODE REVIEW

**Comment by gskema** [comment]
Hi, looks good,
I think we can also remove calls to `bindUniform`; And maybe remove `initUniform` completly since it's only used internally by blocklayered? Do you agree?

**Comment by kpodemski** [comment]
Hi, remove calls but keep it in retro-compatibility, right?

**Comment by gskema** [comment]
Yes, my initial idea was to keep function decalration in `20-compatibility.js`:

``` js
function bindUniform()
{
   // Scream into the abyss
}
```

but remove all calls from theme `bindUniform()`. Custom modules can still though.

**Comment by kpodemski** [comment]
Yep, it is done, please merge if everything is ok in your opinion

**Comment by gskema** [comment]
I think I remember seeing some css rules like `#nbSelector1` or something, which target element modified by uniform. I think we should check for that and maybe check if selects work correctly without uniform (don't collapse they layout)

**Comment by kpodemski** [comment]
@gskema it is simply float: left;, i think it will not be an issue here

**Comment by gskema** [comment]
Where did find it? If it's meant for uniform transformed elements, then we should remove it since, we are cleaning up things

**Comment by kpodemski** [comment]
image

**Pull request merged**
