### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by firstred**
Thanks for your work, @gskema!
Here's a translation :smile:

### CODE REVIEW

**Comment by gskema** [comment]
We've only changed a few translatable strings in front-office.
Did you download the PrestaShop translation and then fill in the missing fields?

**Comment by firstred** [comment]
Yep, it contains all fields.

**Comment by gskema** [comment]
Thanks, you may need to update this sometime in the future, because there will still be some changes

**Comment by firstred** [comment]
Sure thing!

**Pull request merged**
