### PR TITLE
[+] Projects: Add gulp task which finds incorrect Smarty translations

### PR DESCRIPTION
**Pull request by gskema**

### CODE REVIEW

**Comment by kpodemski** [comment]
aaaa :fire: :fire: :fire: :fire: :fire:

**Comment by gskema** [comment]
I'll add `/modules/` path too

**Comment by gskema** [comment]
Permission to merge?

**Comment by kpodemski** [comment]
I didn't test it but if that works this is a killer PR :)

:fire:

**Comment by gskema** [comment]
Works well but sometimes there are false positive, for example if there's a `}` in the middle of the string then the RegEx things that's the end of the expression

**Comment by kpodemski** [comment]
Can we just look for `'}`? Or `"}`?

**Pull request merged**
