### PR TITLE
Fix : click on color label reset the filter

### PR DESCRIPTION
**Pull request by CedCannes**
Colors' labels contain a link and the click on it should be ignored.

### CODE REVIEW

**Comment by gskema** [comment]
Hello, thank you for your contribution.
1. Is this causing a bug for you?
2. Function is missing the `e` parameter.
3. `e.preventDefault` should be used on `a` element directly, not on `label`
4. Filter URLs should start with `#/`, but they start with `#` now

**Comment by CedCannes** [comment]
Hello, 

In fact, I have a problem with the theme-default bootstrap and saw after submitting my line in the PR directly by github that it was not the same theme sorry.

My bug was : if I activate the blocklayered module and I filter the colors with checkbox mode, the filter works if I click on the color's icon but if I click on the label the filter is reset (and 2 Request are fired instead of 1).

This modification fix the bug with the bootstrap theme-default but may be useless for the community theme that I have not test, sorry.

``` php
// Click on color
    $(document).on('click', '#layered_form input[type=button], #layered_form label.layered_color', function(e) {
        e.preventDefault();
        if (!$('input[name='+$(this).attr('name')+'][type=hidden]').length)
            $('<input />').attr('type', 'hidden').attr('name', $(this).attr('name')).val($(this).data('rel')).appendTo('#layered_form');
        else
            $('input[name='+$(this).attr('name')+'][type=hidden]').remove();
        reloadContent(true);
    });

```

**Comment by CedCannes** [comment]
So I will install this theme that look much better than the default theme :)

**Comment by CedCannes** [comment]
I think my bug is caused by my installation of prestashop because by trying the online demo PrestaShop here : http://fo.demo.prestashop.com/fr/8-dresses#/color-orange  I do not see the bug :(.

So this PR is useless, sorry.

**Comment by CedCannes** [comment]
Error was a wrong redirection rule in my apache vhost.conf .

**Comment by gskema** [comment]
@CedCannes There are actually related bugs with this label and the filter URL, it strange that it's even working

**Comment by CedCannes** [comment]
Yes, you're right : It's strange that it's even working. :+1:

**Comment by CedCannes** [comment]
I finally kept this PR on my project
I explain why here : https://github.com/PrestaShop/PrestaShop/pull/6946#issuecomment-269520715

**Comment by gskema** [comment]
ping @kpodemski

**Comment by kpodemski** [comment]
Makes sens @CedCannes - thank you!

**Pull request merged**
